version: "3.9"
services:
  postgresql12:
    image: postgres:12
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - /tmp/data:/var/lib/postgresql/data
      - /tmp/backup:/var/lib/postgresql/backup
