apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rbac-role
  namespace: test-rbac
subjects:
  - kind: User
    name: test_rbac
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: test-rbac-role
  apiGroup: rbac.authorization.k8s.io
---