apiVersion: v1
kind: Service
metadata:
  name: netology-kube
spec:
  selector:
    app: netology-kube
  ports:
    - name: nginx-http
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-http
      protocol: TCP
      port: 9002
      targetPort: 8080
  type: NodePort
---