 Vagrant.configure("2") do |config|
 	config.vm.box = "bento/ubuntu-20.04"
 	config.vm.network "forwarded_port", guest: 19999, host: 19999
    config.vm.provider "virtualbox" do |vb|
       vb.cpus = "4"
       vb.memory = "4096"
    end
 end