apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-kube
  labels:
    app: netology-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-kube
  template:
    metadata:
      labels:
        app: netology-kube
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "1"
      - name: multitool
        image: wbitt/network-multitool
        env:
            - name: HTTP_PORT
              value: "1180"
            - name: HTTPS_PORT
              value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "1"
---