---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - name: grafana-http
      protocol: TCP
      nodePort: 30101
      port: 3000
      targetPort: 3000
  type: NodePort
